apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: experiment-argocd-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/firatkucuk/experiment-argocd.git
    targetRevision: HEAD
  destination: 
    server: https://kubernetes.default.svc
    namespace: experiment-argocd

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
