apiVersion: apps/v1	
kind: Deployment
metadata:
  name: experiment-argocd-deployment
  labels:
    app: experiment-argocd-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: experiment-argocd-deployment
  template:
    metadata:
      labels:
        app: experiment-argocd-deployment
    spec:
      containers:
      - name: experiment-argocd-deployment
        image:  ghcr.io/firatkucuk/experiment-argocd:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
